// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs compare-text`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "format-json",
    "icon": "📐",
    "name": {
      "en": "Format JSON",
      "ja": "JSON整形",
      "zh": "格式化 JSON",
      "de": "JSON formatieren",
      "es": "Formatear JSON"
    },
    "desc": {
      "en": "Pretty-print, validate, or minify JSON.",
      "ja": "JSONを整形・検証・圧縮。",
      "zh": "美化打印、校验或压缩 JSON。",
      "de": "JSON formatieren, validieren oder minimieren.",
      "es": "Formatea, valida o minifica JSON."
    }
  },
  {
    "slug": "compare-xlsx",
    "icon": "⚖️",
    "name": {
      "en": "Compare Excel Workbooks",
      "ja": "Excel比較",
      "zh": "比较 Excel 工作簿",
      "de": "Excel-Arbeitsmappen vergleichen",
      "es": "Comparar libros de Excel"
    },
    "desc": {
      "en": "Compare two Excel workbooks cell by cell, sheet by sheet.",
      "ja": "2つのExcelブックをシート・セル単位で比較。",
      "zh": "按工作表和单元格逐一比较两个 Excel 工作簿。",
      "de": "Vergleicht zwei Excel-Arbeitsmappen Blatt für Blatt, Zelle für Zelle.",
      "es": "Compara dos libros de Excel hoja por hoja, celda por celda."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'compare-text';
